<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.17763.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <MinimumPlatformVersion>10.0.17763.0</MinimumPlatformVersion>
    <StartupObject>ProjApp.App</StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\Fonts\Phosphor-Fill.ttf" />
    <None Remove="Assets\Fonts\Phosphor.ttf" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\Fonts\Phosphor-Fill.ttf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Fonts\Phosphor.ttf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SurMath\SurMath.csproj" />
  </ItemGroup>

</Project>